# Generated by Django 2.2.3 on 2019-09-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='P_img',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
